/* crops.js — crop catalog for Master Gardener.
   dtm   = days to maturity (first harvest). `from` says whether that count starts at transplant or at sowing.
   s2t   = typical days from sowing to transplant size; added when you direct-seed a transplant-counted crop.
   base  = growing-degree-day base temperature (°F). gdd = approximate GDD band to first harvest (informational only).
   stages = which stage vocabulary applies (fruit / leafy / root / head / flower / perennial). */
window.CROP_GROUPS = {
  tomato:   { name: 'Tomatoes',                 color: '#d94848' },
  brassica: { name: 'Broccoli & cabbage family', color: '#1a9a90' },
  cucurbit: { name: 'Squash, cukes & melons',   color: '#a8830f' },
  root:     { name: 'Roots, bulbs & tubers',    color: '#9463e0' },
  leafy:    { name: 'Leafy greens & herbs',     color: '#3a9e5a' },
  other:    { name: 'Beans, corn & flowers',    color: '#3b82e6' },
  berry:    { name: 'Berries & perennials',     color: '#d43f86' },
  pepper:   { name: 'Peppers & eggplant',       color: '#c97614' },
};

window.STAGES = {
  fruit:     [[0.15, 'Establishing'], [0.45, 'Vegetative growth'], [0.65, 'Flowering'], [0.85, 'Fruit set'], [1.0, 'Ripening'], [1.3, 'Harvest window'], [Infinity, 'Past window']],
  leafy:     [[0.25, 'Establishing'], [0.6, 'Leafing out'], [0.85, 'Baby leaf'], [1.0, 'Sizing up'], [1.4, 'Harvest window'], [Infinity, 'Bolt risk']],
  root:      [[0.2, 'Establishing'], [0.55, 'Top growth'], [0.85, 'Bulking'], [1.0, 'Sizing up'], [1.4, 'Harvest window'], [Infinity, 'Over-mature']],
  head:      [[0.2, 'Establishing'], [0.6, 'Vegetative growth'], [0.9, 'Heading'], [1.0, 'Head forming'], [1.25, 'Harvest window'], [Infinity, 'Bolt risk']],
  flower:    [[0.2, 'Establishing'], [0.6, 'Vegetative growth'], [0.9, 'Budding'], [1.3, 'Blooming'], [Infinity, 'Deadhead / reseed']],
  perennial: [[Infinity, 'Perennial']],
};

/* Fraction of DTM at which fruiting crops typically start setting fruit (for the "until fruiting" estimate). */
window.FRUIT_SET_FRACTION = 0.65;

window.CROPS = [
  { key: 'tomato', name: 'Tomato', emoji: '🍅', group: 'tomato', stages: 'fruit', from: 'transplant', dtm: 75, s2t: 42, base: 50, gdd: [1400, 1600],
    varieties: [{ name: 'Roma', dtm: 85, note: 'determinate' }, { name: 'Large Red Cherry', dtm: 70, note: 'indeterminate' }, { name: 'San Marzano', dtm: 80 }, { name: 'Cherry', dtm: 65 }, { name: 'Celebrity', dtm: 70 }, { name: 'Better Boy', dtm: 75 }, { name: 'Beefsteak', dtm: 85 }],
    tips: ['Stake or cage before fruit weight and summer storms: 5-6 ft stakes, loose ties every 8-12 in.', 'Highs above 90°F cause blossom drop. That is heat, not a nutrient problem.', 'Pinch suckers if you like; leave woody flowering leaders and self-rooted stems.', 'Never follow potatoes or peppers in the same bed two years running (late blight).'] },
  { key: 'pepper', name: 'Pepper', emoji: '🌶️', group: 'pepper', stages: 'fruit', from: 'transplant', dtm: 75, s2t: 56, base: 50, gdd: [1500, 2000],
    varieties: [{ name: 'Jalapeño Early', dtm: 65 }, { name: 'Pasilla Bajo', dtm: 80 }, { name: 'Bell', dtm: 75 }, { name: 'Cayenne', dtm: 72 }, { name: 'Banana', dtm: 70 }, { name: 'Poblano', dtm: 80 }, { name: 'Serrano', dtm: 75 }, { name: 'Habanero', dtm: 95 }],
    tips: ['Small, stocky plant: pinch the central king bud. Tall, leggy plant: top the growing tip (cut 1/4 in above the first full node, take only the top 2-4 in).', 'Leggy usually means under 6 hours of direct sun.', 'Pull dense clover or mulch back a few inches from the stems.', 'Highs above 90°F cause blossom drop; it passes when the heat does.'] },
  { key: 'eggplant', name: 'Eggplant', emoji: '🍆', group: 'pepper', stages: 'fruit', from: 'transplant', dtm: 70, s2t: 56, base: 50,
    varieties: [{ name: 'Black Beauty', dtm: 75 }, { name: 'Ichiban', dtm: 60 }], tips: ['Harvest while skin is glossy; dull skin means over-mature and bitter.'] },
  { key: 'zucchini', name: 'Zucchini / summer squash', emoji: '🥒', group: 'cucurbit', stages: 'fruit', from: 'seed', dtm: 50, base: 50, gdd: [800, 1000],
    varieties: [{ name: 'Black Beauty', dtm: 50 }, { name: 'Yellow Crookneck', dtm: 50 }, { name: 'Yellow Straightneck', dtm: 50 }, { name: 'Costata Romanesco', dtm: 55 }],
    tips: ['Scout the stem base weekly for frass or holes (squash vine borer). Preventive spinosad or Bt drench every 7-10 days.', 'White speckling on the TOP of leaves is natural variegation, not mildew; check the undersides for true powdery mildew.', 'Blossom drop with no fruit set: hand-pollinate in the morning.', 'Plant in a corner so it can sprawl outside the bed.'] },
  { key: 'cucumber', name: 'Cucumber', emoji: '🥒', group: 'cucurbit', stages: 'fruit', from: 'seed', dtm: 55, base: 50, gdd: [900, 1100],
    varieties: [{ name: 'Marketmore 76', dtm: 65 }, { name: 'Straight Eight', dtm: 60 }, { name: 'Boston Pickling', dtm: 55 }], tips: ['Pick every other day once bearing; missed fruit shuts down production.'] },
  { key: 'pumpkin', name: 'Pumpkin', emoji: '🎃', group: 'cucurbit', stages: 'fruit', from: 'seed', dtm: 100, base: 50,
    varieties: [{ name: "Jack O'Lantern", dtm: 100 }, { name: 'Sugar Pie', dtm: 95 }, { name: 'Howden', dtm: 115 }], tips: ['4-5 hills, 6-8 ft apart, on the sunny side of a fence; let vines sprawl into the yard.'] },
  { key: 'winter-squash', name: 'Winter squash', emoji: '🎃', group: 'cucurbit', stages: 'fruit', from: 'seed', dtm: 95, base: 50,
    varieties: [{ name: 'Butternut', dtm: 100 }, { name: 'Acorn', dtm: 85 }, { name: 'Spaghetti', dtm: 90 }], tips: ['Ripe when the rind resists a fingernail; cure in the sun a week before storing.'] },
  { key: 'watermelon', name: 'Watermelon', emoji: '🍉', group: 'cucurbit', stages: 'fruit', from: 'seed', dtm: 85, base: 50,
    varieties: [{ name: 'Sugar Baby', dtm: 75 }, { name: 'Crimson Sweet', dtm: 85 }, { name: 'Jubilee', dtm: 95 }], tips: ['Ripe when the tendril nearest the fruit dries and the ground spot turns yellow.'] },
  { key: 'cantaloupe', name: 'Cantaloupe', emoji: '🍈', group: 'cucurbit', stages: 'fruit', from: 'seed', dtm: 80, base: 50,
    varieties: [{ name: 'Hales Best', dtm: 85 }, { name: 'Ambrosia', dtm: 86 }], tips: ['Ripe when it slips from the vine with light thumb pressure.'] },
  { key: 'okra', name: 'Okra', emoji: '🌿', group: 'other', stages: 'fruit', from: 'seed', dtm: 55, base: 60,
    varieties: [{ name: 'Clemson Spineless', dtm: 56 }, { name: 'Emerald', dtm: 58 }], tips: ['Pick pods at 2-4 in, every other day. Loves the heat you dread.'] },
  { key: 'bush-bean', name: 'Bush bean', emoji: '🫘', group: 'other', stages: 'fruit', from: 'seed', dtm: 55, base: 50,
    varieties: [{ name: 'Blue Lake Bush', dtm: 55 }, { name: 'Contender', dtm: 50 }, { name: 'Provider', dtm: 50 }], tips: ['Succession-sow every 2-3 weeks for a steady harvest.'] },
  { key: 'pole-bean', name: 'Pole bean', emoji: '🫘', group: 'other', stages: 'fruit', from: 'seed', dtm: 65, base: 50,
    varieties: [{ name: 'Kentucky Wonder', dtm: 65 }, { name: 'Blue Lake Pole', dtm: 60 }, { name: 'Rattlesnake', dtm: 70 }], tips: ['Trellis at planting time, not after the vines start reaching.'] },
  { key: 'pea', name: 'Pea', emoji: '🫛', group: 'other', stages: 'fruit', from: 'seed', dtm: 60, base: 40,
    varieties: [{ name: 'Sugar Snap', dtm: 62 }, { name: 'Little Marvel', dtm: 60 }, { name: 'Oregon Sugar Pod', dtm: 65 }], tips: ['Cool-season crop: sow in fall or late winter here; summer heat ends it.'] },
  { key: 'corn', name: 'Sweet corn', emoji: '🌽', group: 'other', stages: 'fruit', from: 'seed', dtm: 80, base: 50, gdd: [1400, 1700],
    varieties: [{ name: 'Silver Queen', dtm: 92 }, { name: 'Golden Bantam', dtm: 80 }, { name: 'Peaches and Cream', dtm: 83 }], tips: ['Plant in blocks (at least 4x4) for wind pollination; single rows make patchy ears.'] },
  { key: 'spinach', name: 'Spinach', emoji: '🥬', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 45, base: 40,
    varieties: [{ name: 'Butterflay', dtm: 45 }, { name: 'Bloomsdale', dtm: 45 }, { name: 'Space', dtm: 40 }], tips: ['Partial shade (raspberry canes work) slows bolting.', 'Cut outer leaves and it keeps coming.'] },
  { key: 'lettuce', name: 'Lettuce', emoji: '🥬', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 50, base: 40,
    varieties: [{ name: 'Buttercrunch', dtm: 55 }, { name: 'Black Seeded Simpson', dtm: 45 }, { name: 'Romaine', dtm: 60 }], tips: ['Bitter leaves mean it is about to bolt; harvest now.'] },
  { key: 'kale', name: 'Kale', emoji: '🥬', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 55, base: 40,
    varieties: [{ name: 'Lacinato', dtm: 60 }, { name: 'Red Russian', dtm: 50 }, { name: 'Winterbor', dtm: 60 }], tips: ['Sweeter after a light frost.'] },
  { key: 'chard', name: 'Swiss chard', emoji: '🥬', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 55, base: 40,
    varieties: [{ name: 'Bright Lights', dtm: 55 }, { name: 'Fordhook Giant', dtm: 60 }], tips: ['Takes the heat better than spinach; harvest outer stalks.'] },
  { key: 'collards', name: 'Collards', emoji: '🥬', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 65, base: 40,
    varieties: [{ name: 'Georgia Southern', dtm: 75 }, { name: 'Vates', dtm: 65 }], tips: ['A Southern fall staple; frost improves flavor.'] },
  { key: 'arugula', name: 'Arugula', emoji: '🥬', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 40, base: 40, varieties: [], tips: ['Bolts fast in heat; sow small amounts often.'] },
  { key: 'mustard', name: 'Mustard greens', emoji: '🥬', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 45, base: 40, varieties: [{ name: 'Southern Giant Curled', dtm: 45 }], tips: [] },
  { key: 'microgreens', name: 'Microgreens', emoji: '🌱', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 12, base: 40, indoor: true, varieties: [{ name: 'Mild Mix', dtm: 12 }], tips: ['Indoor tray only; never the beds.'] },
  { key: 'broccoli', name: 'Broccoli', emoji: '🥦', group: 'brassica', stages: 'head', from: 'transplant', dtm: 60, s2t: 35, base: 40,
    varieties: [{ name: 'DeCicco', dtm: 48 }, { name: 'Calabrese', dtm: 65 }, { name: 'Waltham 29', dtm: 85 }], tips: ['Zone 8a fall crop: transplant in August-September.', 'Cut the main head while the buds are tight; side shoots follow for weeks.'] },
  { key: 'cauliflower', name: 'Cauliflower', emoji: '🥦', group: 'brassica', stages: 'head', from: 'transplant', dtm: 65, s2t: 35, base: 40,
    varieties: [{ name: 'Snowball', dtm: 60 }], tips: ['Tie the leaves over the head to blanch it once it is fist-sized.'] },
  { key: 'cabbage', name: 'Cabbage', emoji: '🥬', group: 'brassica', stages: 'head', from: 'transplant', dtm: 70, s2t: 35, base: 40,
    varieties: [{ name: 'Early Jersey Wakefield', dtm: 63 }, { name: 'Copenhagen Market', dtm: 70 }], tips: ['Harvest when the head is firm to a squeeze; split heads mean too much water too late.'] },
  { key: 'brussels', name: 'Brussels sprouts', emoji: '🥬', group: 'brassica', stages: 'head', from: 'transplant', dtm: 90, s2t: 35, base: 40, varieties: [{ name: 'Long Island Improved', dtm: 90 }], tips: ['Long season; best started for fall and harvested after frost.'] },
  { key: 'carrot', name: 'Carrot', emoji: '🥕', group: 'root', stages: 'root', from: 'seed', dtm: 70, base: 40,
    varieties: [{ name: 'Danvers #126', dtm: 70 }, { name: 'Scarlet Nantes', dtm: 68 }, { name: 'Chantenay', dtm: 70 }], tips: ['Keep the seedbed moist for the whole 14-21 day germination.', 'Onions nearby deter carrot fly.'] },
  { key: 'beet', name: 'Beet', emoji: '🟣', group: 'root', stages: 'root', from: 'seed', dtm: 55, base: 40,
    varieties: [{ name: 'Detroit Dark Red', dtm: 58 }, { name: 'Chioggia', dtm: 55 }], tips: ['Thin to 3 in; each seed is a cluster.'] },
  { key: 'radish', name: 'Radish', emoji: '🔴', group: 'root', stages: 'root', from: 'seed', dtm: 28, base: 40,
    varieties: [{ name: 'Cherry Belle', dtm: 22 }, { name: 'French Breakfast', dtm: 25 }, { name: 'Daikon', dtm: 60 }], tips: ['Pull on time; a week late and they go woody.'] },
  { key: 'turnip', name: 'Turnip', emoji: '⚪', group: 'root', stages: 'root', from: 'seed', dtm: 50, base: 40, varieties: [{ name: 'Purple Top', dtm: 55 }], tips: [] },
  { key: 'potato', name: 'Potato', emoji: '🥔', group: 'root', stages: 'root', from: 'seed', dtm: 90, base: 40,
    varieties: [{ name: 'Yukon Gold', dtm: 80 }, { name: 'Red Pontiac', dtm: 90 }, { name: 'Kennebec', dtm: 90 }, { name: 'Russet', dtm: 100 }], tips: ['Keep in a separate bed from tomatoes (late blight).', 'Hill soil up the stems as they grow; harvest 2 weeks after the tops die back.'] },
  { key: 'sweet-potato', name: 'Sweet potato', emoji: '🍠', group: 'root', stages: 'root', from: 'transplant', dtm: 100, s2t: 0, base: 60,
    varieties: [{ name: 'Beauregard', dtm: 90 }, { name: 'Georgia Jet', dtm: 90 }], tips: ['Dig before soil temps drop below 55°F; cure warm and humid for 10 days.'] },
  { key: 'onion', name: 'Onion', emoji: '🧅', group: 'root', stages: 'root', from: 'transplant', dtm: 100, s2t: 56, base: 40,
    varieties: [{ name: 'Red Burgundy', dtm: 100 }, { name: 'Texas 1015Y', dtm: 110 }, { name: 'White Bermuda', dtm: 95 }, { name: 'Evergreen Bunching', dtm: 65 }], tips: ['Short-day types for zone 8a; plant sets or transplants in fall or late winter.'] },
  { key: 'garlic', name: 'Garlic', emoji: '🧄', group: 'root', stages: 'root', from: 'seed', dtm: 240, base: 40,
    varieties: [{ name: 'Softneck', dtm: 240 }, { name: 'Hardneck', dtm: 240 }], tips: ['Plant cloves October-November; harvest when the lower third of leaves brown.'] },
  { key: 'blackberry', name: 'Blackberry', emoji: '🍇', group: 'berry', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [{ name: 'Natchez' }, { name: 'Ouachita' }, { name: 'Kiowa' }], tips: ['Cut floricanes to the ground after they fruit; keep this year\'s primocanes.'] },
  { key: 'raspberry', name: 'Raspberry', emoji: '🍇', group: 'berry', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [{ name: 'Heritage' }, { name: 'Dorman Red' }], tips: ['Its shade is useful: spinach on the shady side bolts later.'] },
  { key: 'strawberry', name: 'Strawberry', emoji: '🍓', group: 'berry', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [{ name: 'Chandler' }, { name: 'Seascape' }], tips: ['Plant in fall here; pinch first-year runners for bigger crowns.'] },
  { key: 'blueberry', name: 'Blueberry', emoji: '🫐', group: 'berry', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [{ name: 'Rabbiteye' }, { name: 'Southern Highbush' }], tips: ['Needs acidic soil (pH 4.5-5.5); water with rain or acidified water.'] },
  { key: 'fig', name: 'Fig', emoji: '🌳', group: 'berry', stages: 'perennial', from: 'transplant', dtm: 0, base: 50, varieties: [{ name: 'Celeste' }, { name: 'Brown Turkey' }, { name: 'LSU Purple' }], tips: ['Celeste and LSU Purple are the reliable ones this far north of the Gulf.'] },
  { key: 'asparagus', name: 'Asparagus', emoji: '🌿', group: 'berry', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [{ name: 'Jersey Knight' }, { name: 'UC 157' }], tips: ['No harvest year one, light harvest year two, full harvest from year three.'] },
  { key: 'basil', name: 'Basil', emoji: '🌿', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 60, base: 50, varieties: [{ name: 'Genovese', dtm: 68 }, { name: 'Thai', dtm: 64 }], tips: ['Pinch flower spikes to keep it leafy.'] },
  { key: 'cilantro', name: 'Cilantro', emoji: '🌿', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 50, base: 40, varieties: [{ name: 'Slow Bolt', dtm: 50 }], tips: ['Bolts in heat; grow it fall through spring here.'] },
  { key: 'parsley', name: 'Parsley', emoji: '🌿', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 75, base: 40, varieties: [{ name: 'Italian Flat Leaf', dtm: 75 }], tips: ['Slow to germinate (up to 3 weeks); soak seed overnight.'] },
  { key: 'dill', name: 'Dill', emoji: '🌿', group: 'leafy', stages: 'leafy', from: 'seed', dtm: 60, base: 40, varieties: [{ name: 'Bouquet', dtm: 60 }], tips: ['Let a plant or two flower for swallowtails and next year\'s volunteers.'] },
  { key: 'mint', name: 'Mint', emoji: '🌿', group: 'leafy', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [], tips: ['Container only unless you want a mint bed forever.'] },
  { key: 'rosemary', name: 'Rosemary', emoji: '🪴', group: 'leafy', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [{ name: 'Arp' }, { name: 'Tuscan Blue' }], tips: ['Arp is the cold-hardy one for zone 8a.'] },
  { key: 'thyme', name: 'Thyme', emoji: '🪴', group: 'leafy', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [], tips: [] },
  { key: 'oregano', name: 'Oregano', emoji: '🪴', group: 'leafy', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [], tips: [] },
  { key: 'chives', name: 'Chives', emoji: '🌿', group: 'leafy', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [], tips: [] },
  { key: 'marigold', name: 'Marigold', emoji: '🌼', group: 'other', stages: 'flower', from: 'seed', dtm: 50, base: 50, varieties: [{ name: 'French', dtm: 50 }, { name: 'African', dtm: 60 }], tips: ['Companion for tomatoes and peppers; deadhead to keep blooming.'] },
  { key: 'sunflower', name: 'Sunflower', emoji: '🌻', group: 'other', stages: 'flower', from: 'seed', dtm: 80, base: 50, varieties: [{ name: 'Mammoth', dtm: 90 }, { name: 'Teddy Bear', dtm: 70 }], tips: ['Plant on the north side so it does not shade the bed.'] },
  { key: 'zinnia', name: 'Zinnia', emoji: '🌸', group: 'other', stages: 'flower', from: 'seed', dtm: 60, base: 50, varieties: [], tips: ['Cut often; more cutting, more blooms.'] },
  { key: 'nasturtium', name: 'Nasturtium', emoji: '🌸', group: 'other', stages: 'flower', from: 'seed', dtm: 55, base: 50, varieties: [], tips: ['Trap crop for aphids; leaves and flowers are edible.'] },
  { key: 'venus-flytrap', name: 'Venus flytrap', emoji: '🪴', group: 'berry', stages: 'perennial', from: 'transplant', dtm: 0, base: 40, varieties: [], tips: ['Distilled, rain, or RO water only. Morning sun only in Texas heat. No fertilizer.', 'One black lower leaf is normal; trim it at the base.'] },
  { key: 'custom', name: 'Other / custom', emoji: '🌱', group: 'other', stages: 'fruit', from: 'seed', dtm: 60, base: 50, varieties: [], tips: [] },
];

window.cropByKey = key => window.CROPS.find(c => c.key === key) || window.CROPS[window.CROPS.length - 1];
